#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'NON_ALPHA_NUM_WHITE_COUNT' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING inp_str as parameter.
#

def NON_ALPHA_NUM_WHITE_COUNT(inp_str):
    
     cnt =0
     for i in range(len(inp_str)):
        if inp_str[i].isalnum() or inp_str[i].isspace():
            continue 
        else:
                cnt = cnt + 1
                
                
     return cnt

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    inp_str = input()

    count = NON_ALPHA_NUM_WHITE_COUNT(inp_str)

    fptr.write(str(count) + '\n')

    fptr.close()
