from collections import deque
queue = deque()
queue.append('g')
queue.append('f')
queue.append('a')
print("Intial queue")
print(queue)
print("\nelments dequeued from the queue")
print(queue.popleft())
print(queue.popleft())
print(queue.popleft())
print("\nqueue after removing elements")
print(queue)
queue.extend(['a','b','c'])
print("\nQueue after adding multiple elements:")
print(queue)
queue.rotate(1)
print("\nQueue after rotating to the right by 1:")
print(queue)
queue.rotate(-1)
print("\nQueue after rotating to the left by 1:")
print(queue)
queue.reverse()
print("\nQueue after reversing:")
print(queue)
queue.clear()
print("\nQueue after clearing:")
print(queue)
